# Generated by Django 5.2.6 on 2025-10-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aestheticanalysis",
            name="user",
        ),
        migrations.RemoveField(
            model_name="conversationanalysis",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
