# Generated by Django 5.2.6 on 2025-10-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_user_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPUsageTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("first_used", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_used"],
            },
        ),
        migrations.AddField(
            model_name="aestheticanalysis",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversationanalysis",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
