# Generated by Django 5.2.6 on 2025-10-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_add_ip_usage_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=64, unique=True)),
                ("count", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_updated"],
            },
        ),
        migrations.DeleteModel(
            name="IPUsageTracker",
        ),
        migrations.RemoveField(
            model_name="aestheticanalysis",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="conversationanalysis",
            name="ip_address",
        ),
    ]
